### ISSUE TITLE
Question about sorting

### ISSUE THREAD

**Issue by schoettker** [debanjum/company-ledger#1]
Hey thanks for the great package!
I was wondering if you could help me with reversing the sorting of the candidates. I've tried playing with reversing the sequence of candidates explicitly, but couldn't get it to work. According to company this  [line](https://github.com/debanjum/company-ledger/blob/1df655abd67d2b75016794f97bdfbe0dda58d6fa/company-ledger.el#L112) prevents additional sorting by company itself, so I am not sure why the reversal is not working.
My use case for this is, that I add transactions at the bottom of the file and usually the most recent similar transaction is closest to what I'm adding.

Edit: This seems to be a Doom Emacs issue which uses a custom (+company/complete) function. On vanilla company-ledger already does sort in reverse order. If it's okay I would let this issue stay open and maybe follow up with a workaround solution later

Edit 2: Maybe not solely Doom Emacs issue because it also is not sorted reversely when `company-complete` is run. If anyone needs a quick workaround, I use the following for now in beancount major mode:

```
  (setq company-idle-delay nil)
  (map! :map beancount-mode-map
        :i "TAB" #'company-ledger
        :i "C-SPC" #'company-ledger
        :i "C-N" #'company-ledger
        )

```

Emacs Version 27.1

**Comment by debanjum** [comment]
Hey @schoettkr,
- `company-ledger` reverse sorts the candidates by default. So the bottom most candidate should show up first.
   Unsure of why it didn't do this for you, both auto-completion and manual trigger of `company-complete` reverse sort the candidates for me
- Glad that you've found a workaround! Though unsure of how/why that specific config works. 🤔 
   I noticed I had `(setq company-idle-delay 0)` set in my [init.el](https://gist.githubusercontent.com/debanjum/137d45500bd302ff8007f536085fe17d/raw/67ee707a2055aa2cfff2039107f9f84afbcfab6c/init.el) but couldn't repro your issue by setting it back to the default delay of 0.5 
- For future reference, `company-transformers` should allow customizing the sort order of suggested candidates. An [example implementation](https://github.com/company-mode/company-mode/issues/511#issuecomment-219016047) and [this comments](https://github.com/company-mode/company-mode/issues/307#issuecomment-75904417) may help with that.

Let me know if you need further assistance on this? If so, more details may help me repro the behavior.
Otherwise feel free to close this issue!

**Comment by schoettker** [comment]
I was pretty confused by it as well, but also have to admit that I am not really proficient with Elisp haha. I'm just surprised the `company-complete` function gives the candidate list from top to bottom, while triggering `company-ledger` manually reverses them properly. There might be some advice or custom setting which I haven't found yet in the Doom Emacs configuration. Nevertheless I will go ahead and close the issue since this does not seem to stem from company-ledger after all.

Thanks for the advice! Especially in regards to the sorting of grouped backend, because that could really be it!
I might do some additional digging on the next weekend and update my comment, if anyone else comes across this. So far though I was pretty happy even with the workaround when adding last weeks expenses :tada: ! :slightly_smiling_face: 

For the workaround it's just to disable company's autocompletion (which sorts wrong) and relying on manually triggering `company-ledger` instead (which sorts correctly) 

Thanks again, can be closed :yum: 


**Follow-up:** For anyone wondering, if you're using Doom Emacs using Doom's `set-company-backend!` wrapper function is the recommended way to add `company-ledger` to company backends.
 E.g: `(set-company-backend! 'beancount-mode 'company-ledger)`
